version: '3.7'

services:
  nats:
    image: nats
    restart: always
    ports:
      - "4444:4444"
      
  redis_image:
    image: redis
    
    container_name: redis_image
    restart: always
    ports: 
    - "6379:6379"